# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: coronate 0.0.7 ruby lib

Gem::Specification.new do |s|
  s.name = "coronate"
  s.version = "0.0.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eiffel Qiu"]
  s.date = "2013-11-07"
  s.description = "Corona project builder tools"
  s.email = "eiffelqiu@gmail.com"
  s.executables = ["coronate"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "lib/coronate.rb",
    "lib/coronate/builder/app_builder.rb",
    "lib/coronate/builder/ebook_builder.rb",
    "lib/coronate/builder/game_builder.rb",
    "lib/coronate/builder/project_builder.rb",
    "lib/coronate/builder/scene_builder.rb",
    "lib/coronate/builder/templates/app/build.settings.tt",
    "lib/coronate/builder/templates/app/config.lua.tt",
    "lib/coronate/builder/templates/app/icon1-down.png",
    "lib/coronate/builder/templates/app/icon1-down@2x.png",
    "lib/coronate/builder/templates/app/icon1.png",
    "lib/coronate/builder/templates/app/icon1@2x.png",
    "lib/coronate/builder/templates/app/icon2-down.png",
    "lib/coronate/builder/templates/app/icon2-down@2x.png",
    "lib/coronate/builder/templates/app/icon2.png",
    "lib/coronate/builder/templates/app/icon2@2x.png",
    "lib/coronate/builder/templates/app/main.lua.tt",
    "lib/coronate/builder/templates/app/view1.lua.tt",
    "lib/coronate/builder/templates/app/view2.lua.tt",
    "lib/coronate/builder/templates/ebook/build.settings.tt",
    "lib/coronate/builder/templates/ebook/config.lua.tt",
    "lib/coronate/builder/templates/ebook/coronaicon-big.png",
    "lib/coronate/builder/templates/ebook/cover.jpg",
    "lib/coronate/builder/templates/ebook/main.lua.tt",
    "lib/coronate/builder/templates/ebook/moon.png",
    "lib/coronate/builder/templates/ebook/page1.lua.tt",
    "lib/coronate/builder/templates/ebook/pagebg1.png",
    "lib/coronate/builder/templates/ebook/space.jpg",
    "lib/coronate/builder/templates/ebook/sun.png",
    "lib/coronate/builder/templates/ebook/title.lua.tt",
    "lib/coronate/builder/templates/game/background.jpg",
    "lib/coronate/builder/templates/game/build.settings.tt",
    "lib/coronate/builder/templates/game/button-over.png",
    "lib/coronate/builder/templates/game/button.png",
    "lib/coronate/builder/templates/game/config.lua.tt",
    "lib/coronate/builder/templates/game/crate.png",
    "lib/coronate/builder/templates/game/grass.png",
    "lib/coronate/builder/templates/game/level1.lua.tt",
    "lib/coronate/builder/templates/game/logo.png",
    "lib/coronate/builder/templates/game/main.lua.tt",
    "lib/coronate/builder/templates/game/menu.lua.tt",
    "lib/coronate/builder/templates/project/build.settings.tt",
    "lib/coronate/builder/templates/project/config.tt",
    "lib/coronate/builder/templates/project/endingScene.tt",
    "lib/coronate/builder/templates/project/main.tt",
    "lib/coronate/builder/templates/project/menuScene.tt",
    "lib/coronate/builder/templates/project/settingsScene.tt",
    "lib/coronate/builder/templates/project/titleScene.tt",
    "lib/coronate/builder/templates/project/utils.tt",
    "lib/coronate/builder/templates/scene/scene.tt",
    "lib/coronate/cli.rb",
    "lib/coronate/extensions/method_hooker.rb",
    "lib/coronate/extensions/string_extention.rb"
  ]
  s.homepage = "http://github.com/eiffelqiu/coronate"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.9"
  s.summary = "Corona Builder"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.7"])
    else
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
    end
  else
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
  end
end

